/**
 * [Round 94] English names of the abilities whose automation is keyed by a Russian name
 * (songs, alchemist cards, flat heals, auto-learned talents, techniques, stratagems, aspects, weaves).
 * Names only — no rules text. `canon(name)` turns any known spelling into the Russian key the tables use.
 */
import { norm } from "./names.mjs";

/** As printed in the English edition of rulebooks I–III. */
const BOOK = {
  "Расслабляющая": ["Ambience"],
  "Какофония": ["Cacophony"],
  "Баллада": ["Ballad"],
  "Разрыв": ["Break"],
  "Колыбельная": ["Lullaby"],
  "Танец": ["Dance"],
  "Лень": ["Lazy"],
  "Боевой дух": ["Morale"],
  "Сопротивление": ["Resistance"],
  "Транс": ["Trance"],
  "Разрежение": ["Reduction"],
  "Лечебный спрей": ["Heal Spray"],
  "Яркая жидкость": ["Vivid Liquid"],
  "Всходы маны": ["Mana Sprout"],
  "Базовое лечение": ["Basic Healing"],
  "Улучшенное лечение": ["Advanced Healing"],
  "Расширенное лечение": ["Extended Healing"],
  "Насыщенное лечение": ["Rich Heal"],
  "Лечебная вода": ["Healing Water"],
  "Цепная атака": ["Chain Attack"],
  "Встречный удар": ["Counter"],
  "Прочность": ["Toughness"],
  "Мастер боя": ["Battle Master"],
  "Охота за сокровищами": ["Treasure Hunt"],
  "Быстрое действие": ["Fast Action"],
  "Крадущаяся тень": ["Shadow Sneak"],
  "Мастер сокровищ": ["Treasure Master"],
  "Мастер навыков": ["Skill Master"],
  "Выживаемость": ["Survivability"],
  "Неукротимый": ["Indomitable"],
  "Мастер зелий": ["Potion Master"],
  "Сюкути": ["Shukuchi"],
  "Беги и стреляй": ["Run-and-Gun"],
  "Зоркие глаза": ["Keen Eyes"],
  "Использование слабых мест": ["Weakness Exploit"],
  "Экономия маны": ["Mana Save"],
  "Сопротивление мане": ["Mana Resistance"],
  "Премудрость мудреца": ["Sage's Wisdom"],
  "Мастер рун": ["Rune Master"],
  "Кошачьи глаза": ["Cat's Eyes", "Cat's Eye"],
  "Медвежья мышца": ["Bear Muscle"],
  "Восстановление": ["Recovery"],
  "Ядовитая игла": ["Poison Needle"],
};
/**
 * Warleader / Geomancer / Dark Hunter abilities: these classes are not in the English books we have,
 * so these are our own working translations — rename freely, the Russian key is what matters.
 */
const UNOFFICIAL = {
  "Вызывающая Позиция I": ["Defiant Stance I"],
  "Вызывающая Позиция II": ["Defiant Stance II"],
  "Вызывающая Позиция III": ["Defiant Stance III"],
  "Вызывающая Позиция IV": ["Defiant Stance IV"],
  "Вызывающая Позиция V: Эфирная пружина": ["Defiant Stance V: Ether Spring"],
  "Вызывающая Позиция V: Переполненная жизнь": ["Defiant Stance V: Overflowing Life"],
  "Изменчивая Фортуна I": ["Fickle Fortune I"],
  "Изменчивая Фортуна II": ["Fickle Fortune II"],
  "Изменчивая Фортуна III": ["Fickle Fortune III"],
  "Изменчивая Фортуна IV": ["Fickle Fortune IV"],
  "Изменчивая Фортуна V": ["Fickle Fortune V"],
  "Надежная защита II: Железные Доспехи": ["Steadfast Defense II: Iron Armor"],
  "Надежная защита II: Твердая Форма": ["Steadfast Defense II: Solid Form"],
  "Надежная защита III: Бронированный сердечник": ["Steadfast Defense III: Armored Core"],
  "Надежная защита III: Стальные доспехи": ["Steadfast Defense III: Steel Armor"],
  "Надежная защита IV: Доспехи замка": ["Steadfast Defense IV: Castle Armor"],
  "Надежная защита IV: Зеркальный щит": ["Steadfast Defense IV: Mirror Shield"],
  "Надежная защита V: Гигантская стена": ["Steadfast Defense V: Giant Wall"],
  "Надежная защита V: Стальная цитадель": ["Steadfast Defense V: Steel Citadel"],
  "Нарастающее Наступление I": ["Mounting Offensive I"],
  "Нарастающее Наступление II: Яростное Пламя": ["Mounting Offensive II: Raging Flame"],
  "Нарастающее Наступление II: Вихрь": ["Mounting Offensive II: Whirlwind"],
  "Нарастающее Наступление III: Ревущее пламя": ["Mounting Offensive III: Roaring Flame"],
  "Нарастающее Наступление III: Истинная цель": ["Mounting Offensive III: True Aim"],
  "Нарастающее Наступление IV: Пламя": ["Mounting Offensive IV: Blaze"],
  "Нарастающее Наступление IV: Лучезарные удары": ["Mounting Offensive IV: Radiant Strikes"],
  "Нарастающее Наступление V: Тайфун": ["Mounting Offensive V: Typhoon"],
  "Поиск Недостатков": ["Flaw Finding"],
  "Позиция Божественной Скорости": ["Godspeed Stance"],
  "Гимн храбрых": ["Hymn of the Brave"],
  "Тайное возрождение": ["Secret Revival"],
  "Великая задача": ["Grand Task"],
  "Оценка травматизма": ["Injury Assessment"],
  "Стратегическая изобретательность": ["Strategic Ingenuity"],
  "Сплошная линия": ["Unbroken Line"],
  "Сокрушительная победа": ["Crushing Victory"],
  "Тщательная Охрана I": ["Careful Guard I"],
  "Тщательная Охрана II": ["Careful Guard II"],
  "Концентрация I": ["Concentration I"],
  "Концентрация II": ["Concentration II"],
  "Эффективность I": ["Efficiency I"],
  "Эффективность II": ["Efficiency II"],
  "Предвидение I": ["Foresight I"],
  "Предвидение II": ["Foresight II"],
  "Сопротивление I": ["Resistance I"],
  "Сопротивление II": ["Resistance II"],
  "Неожиданный Удар I": ["Surprise Strike I"],
  "Неожиданный Удар II": ["Surprise Strike II"],
  "Исцеляющая Земля": ["Healing Earth"],
  "Нисходящий гром": ["Falling Thunder"],
  "Пожиратель снов": ["Dream Eater"],
  "Обновление": ["Renewal"],
  "Расход маны": ["Mana Drain"],
  "Горный восторг": ["Mountain Rapture"],
  "Песчаный щит": ["Sand Shield"],
  "Ужас": ["Terror"],
  "Направляющие ветры": ["Guiding Winds"],
  "Гнев Тенмы": ["Wrath of Tenma"],
  "Сифон Маны": ["Mana Siphon"],
  "Зыбучий песок": ["Quicksand"],
  "Шаги": ["Footsteps"],
  "Фокус Эссенции": ["Essence Focus"],
  "Техника Связывания Разума I": ["Mind Binding Technique I"],
  "Техника Связывания Разума II": ["Mind Binding Technique II"],
  "Техника Связывания Разума III": ["Mind Binding Technique III"],
  "Спектральный защитный круг": ["Spectral Ward Circle"],
  "Методы Исследования Бездны": ["Abyss Research Methods"],
  "Опека Бедствия": ["Calamity Ward"],
  "Изгоняющая зло световая пуля": ["Evil-Banishing Light Bullet"],
  "Изгоняющее зло световое копье": ["Evil-Banishing Light Spear"],
};

const key = (s) => norm(s).replace(/[’‘`]/g, "'");
const IX = new Map();
for (const table of [BOOK, UNOFFICIAL]) for (const [ru, list] of Object.entries(table)) for (const n of list) IX.set(key(n), ru);

/** Any known spelling -> the Russian table key; unknown names are returned unchanged. */
export const canon = (name) => IX.get(key(name)) ?? name;
/** English name of a Russian key (undefined when there is none). */
export const enName = (ru) => (BOOK[ru] ?? UNOFFICIAL[ru])?.[0];
export const ABILITY_NAMES = { BOOK, UNOFFICIAL };
